// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Femh3X75rsPJD88ymG0TVRVwsIEjP8k',
    appId: '1:627276101240:web:8e1c593e23793344a9df8d',
    messagingSenderId: '627276101240',
    projectId: 'origamier-1578d',
    authDomain: 'origamier-1578d.firebaseapp.com',
    storageBucket: 'origamier-1578d.appspot.com',
    measurementId: 'G-6766FKZCR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOeksYEGppHy9eNn2mATtXCmFGlhdZ3t4',
    appId: '1:627276101240:android:6265c4e800496634a9df8d',
    messagingSenderId: '627276101240',
    projectId: 'origamier-1578d',
    storageBucket: 'origamier-1578d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6gtADWeCHAR3sLhG2XQt3l4Jp7XCRw1M',
    appId: '1:627276101240:ios:6e5a91d073d35097a9df8d',
    messagingSenderId: '627276101240',
    projectId: 'origamier-1578d',
    storageBucket: 'origamier-1578d.appspot.com',
    iosClientId: '627276101240-7j156kkjghflq2fguvafea9nqatuhkgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.origamiers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6gtADWeCHAR3sLhG2XQt3l4Jp7XCRw1M',
    appId: '1:627276101240:ios:6e5a91d073d35097a9df8d',
    messagingSenderId: '627276101240',
    projectId: 'origamier-1578d',
    storageBucket: 'origamier-1578d.appspot.com',
    iosClientId: '627276101240-7j156kkjghflq2fguvafea9nqatuhkgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.origamiers',
  );
}
